apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort  # Cambio importante aquí
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30002  # Puedes definir un puerto entre 30000-32767
